### ISSUE TITLE
Meta-Issue:  Accounting for GCAM to Downstream Model QC

### ISSUE THREAD

**Issue by crvernon** [IMMM-SFA/gcam-usa_to_downstream-models#1]
# Meta-Issue:  Accounting for GCAM to Downstream Model QC

Please link to this issue in all PRs to ensure we are accounting for all relevant QC tasks.

## GCAM to Demeter
- [x] QC:  XPath query for land allocation (#3)
- [x] QC:  XPath query for agricultural production by technology (#4 )
- [x] QC:  XPath query for fertilizer consumption by agricultural technology (#5)

## GCAM to CERF
- [x] QC:  XPath queries for technology capacity expansion (#6) 
- [ ] QC:  XPath query for technology investment-level capacity factors (#7)
- [ ] QC:  XPath query for technology heat rates (#8)
- [ ] QC:  XPath query for technology fuel costs (#9)
- [x] QC:  XPath query for variable O&M cost (#10) 
- [ ] QC:  XPath query for carbon price
- [x] QC:  Exogenous input path for investment-level technology lifetimes (#13) 
- [x] QC:  Exogenous input path for technology carbon capture rates (#11)
- [x] QC:  Exogenous input path for technology fuel CO2 content (#12) 
- [x] QC:  Validate calculate of variable O&M cost escalation rate (#10) 
- [ ] QC:  Validate calculate of fuel cost escalation rate (#9)
- [x] QC:  Validate GDP deflator
- [x] QC:  Validate GCAM-USA grid regions to state mapping

## GCAM to TELL
- [x] QC: Validate extraction of total electricity demand by state; see #2 

## GCAM to GO
- [ ] QC:  XPath query for technology heat rates (#15)
- [ ] QC:  XPath query for technology fuel costs (#14) 
- [ ] QC:  XPath query for carbon price
- [ ] QC:  Exogenous input path for technology carbon capture rates (#11)
- [ ] QC:  Exogenous input path for technology fuel CO2 content (#12) 

## GCAM to Tethys
- [ ] <fill>
